#!/usr/bin/env python3
"""G27: Installer — NSIS script generator for AEGIS NIDS
Generates installer.nsi for NSIS (Nullsoft Scriptable Install System)
"""
import sys

NSIS_TEMPLATE = r'''# AEGIS NIDS Installer (NSIS)
# Generated by G27 installer script
# Build: makensis installer.nsi

!define APPNAME "AEGIS NIDS"
!define APPVERSION "1.0.0"
!define APPPUBLISHER "AEGIS Security"

Name "${APPNAME} ${APPVERSION}"
OutFile "aegis-installer-${APPVERSION}.exe"
InstallDir "$PROGRAMFILES64\AEGIS"
RequestExecutionLevel admin

Page directory
Page instfiles
UninstPage uninstConfirm
UninstPage instfiles

Section "Install"
  SetOutPath "$INSTDIR"
  
  # Runtime files
  File "nids_analyze.zig"
  File "nids_capture.zig"
  File "nids_main.zig"
  File "windows_capture.zig"
  File "build.zig"
  
  # Bridge
  SetOutPath "$INSTDIR\bridge"
  File "bridge\aegis_ipc.hpp"
  File "bridge\aegis_ipc.cpp"
  File "bridge\aegis_bridge_ctypes.py"
  File "bridge\aegis_packet_parser.hpp"
  File "bridge\aegis_packet_parser.cpp"
  File "bridge\aegis_bridge_main.cpp"
  File "CMakeLists.txt"
  
  # Rust
  SetOutPath "$INSTDIR\src"
  File "src\lib.rs"
  File "Cargo.toml"
  
  # Python
  SetOutPath "$INSTDIR"
  File "windows_brain.py"
  File "aegis_daemon.py"
  File "aegis_console.py"
  File "aegisctl.py"
  File "test_e2e.py"
  
  # Go
  File "windows_perf.go"
  File "go.mod"
  
  # Config
  SetOutPath "$INSTDIR\config"
  File "Rules.json"
  
  # Drivers
  SetOutPath "$INSTDIR\drivers\wfp_callout"
  File "drivers\wfp_callout\aegis_wfp.c"
  File "drivers\wfp_callout\aegis_wfp.h"
  File "drivers\wfp_callout\aegis_wfp.inf"
  File "drivers\wfp_callout\aegis_wfp_callout.c"
  File "drivers\wfp_callout\aegis_wfp_comm.c"
  
  SetOutPath "$INSTDIR\drivers\minifilter"
  File "drivers\minifilter\aegis_minifilter.c"
  File "drivers\minifilter\aegis_minifilter.h"
  File "drivers\minifilter\aegis_minifilter.inf"
  File "drivers\minifilter\aegis_minifilter_comm.c"
  File "drivers\minifilter\aegis_minifilter_file.c"
  File "drivers\minifilter\aegis_minifilter_proc.c"
  
  # Build scripts
  SetOutPath "$INSTDIR"
  File "build_all.bat"
  File "build_drivers.bat"
  File "install_drivers.bat"
  File "run_aegis.bat"
  
  # Documentation
  File "runtime_manifest.json"
  
  # Create logs directory
  CreateDirectory "$INSTDIR\logs\pids"
  
  # Preserve existing config
  IfFileExists "$INSTDIR\config\Rules.json.bak" 0 +2
    CopyFiles "$INSTDIR\config\Rules.json" "$INSTDIR\config\Rules.json.bak"
  
  # Create uninstaller
  WriteUninstaller "$INSTDIR\uninstall.exe"
  
  # Start menu shortcuts
  CreateDirectory "$SMPROGRAMS\AEGIS"
  CreateShortcut "$SMPROGRAMS\AEGIS\AEGIS Console.lnk" "$INSTDIR\aegis_console.py"
  CreateShortcut "$SMPROGRAMS\AEGIS\AEGIS Daemon.lnk" "$INSTDIR\aegis_daemon.py"
  CreateShortcut "$SMPROGRAMS\AEGIS\Uninstall.lnk" "$INSTDIR\uninstall.exe"
  
  # Registry
  WriteRegStr HKLM "Software\AEGIS" "InstallDir" "$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" "DisplayName" "${APPNAME}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" "UninstallString" "$INSTDIR\uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" "DisplayVersion" "${APPVERSION}"
  
  MessageBox MB_OK "AEGIS NIDS installed to $INSTDIR$\n$\nNext steps:$\n1. Build: run build_all.bat$\n2. Install drivers: run install_drivers.bat (requires test-signing)$\n3. Start: run run_aegis.bat"
SectionEnd

Section "Uninstall"
  # Stop service if running
  nsExec::ExecToLog "taskkill /im aegis-nids.exe /f"
  nsExec::ExecToLog "taskkill /im python.exe /f"
  
  # Preserve logs
  CreateDirectory "$TEMP\AEGIS_backup"
  CopyFiles "$INSTDIR\logs\anomalous.json" "$TEMP\AEGIS_backup\"
  
  # Remove files
  RMDir /r "$INSTDIR\bridge"
  RMDir /r "$INSTDIR\src"
  RMDir /r "$INSTDIR\config"
  RMDir /r "$INSTDIR\drivers"
  RMDir /r "$INSTDIR\logs"
  RMDir /r "$INSTDIR\docs"
  Delete "$INSTDIR\*.zig"
  Delete "$INSTDIR\*.py"
  Delete "$INSTDIR\*.go"
  Delete "$INSTDIR\*.bat"
  Delete "$INSTDIR\*.json"
  Delete "$INSTDIR\*.toml"
  Delete "$INSTDIR\*.mod"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"
  
  # Remove shortcuts
  RMDir /r "$SMPROGRAMS\AEGIS"
  
  # Remove registry
  DeleteRegKey HKLM "Software\AEGIS"
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS"
  
  MessageBox MB_OK "AEGIS NIDS uninstalled.$\nLogs backed up to $TEMP\AEGIS_backup\"
SectionEnd
'''

if __name__ == "__main__":
    with open("installer.nsi", "w") as f:
        f.write(NSIS_TEMPLATE)
    print("Generated installer.nsi")
    print("Build with: makensis installer.nsi")
    print("Output: aegis-installer-1.0.0.exe")
